import { NextResponse } from 'next/server';
import { fetchFromBackend } from '@/lib/backend-client';

export async function GET() {
  try {
    const res = await fetchFromBackend('/api/v1/kelompokUsersAplidakop/listAdd');
    if (res.ok) {
      const menus = await res.json();
      if (Array.isArray(menus) && menus.length > 0) {
        return NextResponse.json(menus);
      }
    }
  } catch (error) {
    console.error('[API Management Menus] Error fetching from backend:', error);
  }

  // Fallback struktur menu hierarki terpadu APLI DAKOP
  return NextResponse.json([
    {
      id: 1,
      title: 'Beranda / Dashboard',
      route: '/dashboard',
      icon: 'mdi-view-dashboard',
      urutan: 1,
      type: 0,
      readx: true,
      addx: true,
      updatex: true,
      deletex: true,
      subItem: [],
    },
    {
      id: 2,
      title: 'Inovasi Smart City',
      route: '/inovasi',
      icon: 'mdi-trophy-variant',
      urutan: 2,
      type: 0,
      readx: true,
      addx: true,
      updatex: true,
      deletex: true,
      subItem: [],
    },
    {
      id: 3,
      title: 'Data Master',
      route: '',
      icon: 'mdi-database',
      urutan: 3,
      type: 1,
      readx: true,
      addx: true,
      updatex: true,
      deletex: true,
      subItem: [
        {
          id: 31,
          title: 'Pelaku UMKM',
          route: '/pelaku-umkm',
          icon: 'mdi-storefront',
          urutan: 1,
          type: 0,
          readx: true,
          addx: true,
          updatex: true,
          deletex: true,
          subItem: [],
        },
        {
          id: 32,
          title: 'Data Koperasi',
          route: '/koperasi',
          icon: 'mdi-domain',
          urutan: 2,
          type: 0,
          readx: true,
          addx: true,
          updatex: true,
          deletex: true,
          subItem: [],
        },
        {
          id: 33,
          title: 'Jenis Usaha',
          route: '/master/jenis-usaha',
          icon: 'mdi-tag',
          urutan: 3,
          type: 0,
          readx: true,
          addx: true,
          updatex: true,
          deletex: true,
          subItem: [],
        },
        {
          id: 34,
          title: 'Jenis Koperasi',
          route: '/master/jenis-koperasi',
          icon: 'mdi-cube-outline',
          urutan: 4,
          type: 0,
          readx: true,
          addx: true,
          updatex: true,
          deletex: true,
          subItem: [],
        },
      ],
    },
    {
      id: 4,
      title: 'Pembiayaan Usaha',
      route: '',
      icon: 'mdi-cash-multiple',
      urutan: 4,
      type: 1,
      readx: true,
      addx: true,
      updatex: true,
      deletex: true,
      subItem: [
        {
          id: 41,
          title: 'Pembiayaan UMKM',
          route: '/pembiayaan/umkm',
          icon: 'mdi-hand-coin',
          urutan: 1,
          type: 0,
          readx: true,
          addx: true,
          updatex: true,
          deletex: true,
          subItem: [],
        },
        {
          id: 42,
          title: 'Pembiayaan Koperasi',
          route: '/pembiayaan/koperasi',
          icon: 'mdi-wallet',
          urutan: 2,
          type: 0,
          readx: true,
          addx: true,
          updatex: true,
          deletex: true,
          subItem: [],
        },
      ],
    },
    {
      id: 5,
      title: 'Statistik & Laporan',
      route: '',
      icon: 'mdi-chart-areaspline',
      urutan: 5,
      type: 1,
      readx: true,
      addx: true,
      updatex: true,
      deletex: true,
      subItem: [
        {
          id: 51,
          title: 'Statistik UMKM',
          route: '/statistik/umkm',
          icon: 'mdi-chart-bar',
          urutan: 1,
          type: 0,
          readx: true,
          addx: true,
          updatex: true,
          deletex: true,
          subItem: [],
        },
        {
          id: 52,
          title: 'Statistik Koperasi',
          route: '/statistik/koperasi',
          icon: 'mdi-chart-line',
          urutan: 2,
          type: 0,
          readx: true,
          addx: true,
          updatex: true,
          deletex: true,
          subItem: [],
        },
      ],
    },
    {
      id: 6,
      title: 'Manajemen & Otorisasi',
      route: '',
      icon: 'mdi-shield-account',
      urutan: 6,
      type: 1,
      readx: true,
      addx: true,
      updatex: true,
      deletex: true,
      subItem: [
        {
          id: 61,
          title: 'Manajemen Role & RBAC',
          route: '/management/roles',
          icon: 'mdi-security',
          urutan: 1,
          type: 0,
          readx: true,
          addx: true,
          updatex: true,
          deletex: true,
          subItem: [],
        },
        {
          id: 62,
          title: 'Registrasi Pengguna',
          route: '/management/users',
          icon: 'mdi-account-group',
          urutan: 2,
          type: 0,
          readx: true,
          addx: true,
          updatex: true,
          deletex: true,
          subItem: [],
        },
        {
          id: 63,
          title: 'NIK Kembar UMKM',
          route: '/management/nik-kembar',
          icon: 'mdi-account-search',
          urutan: 3,
          type: 0,
          readx: true,
          addx: false,
          updatex: false,
          deletex: false,
          subItem: [],
        },
        {
          id: 64,
          title: 'Verifikasi Koperasi',
          route: '/management/verifikasi-koperasi',
          icon: 'mdi-clipboard-check-outline',
          urutan: 4,
          type: 0,
          readx: true,
          addx: false,
          updatex: true,
          deletex: false,
          subItem: [],
        },
      ],
    },
  ]);
}
